### ISSUE TITLE
安卓 9 上,微信是无法启动的-_-||

### ISSUE THREAD

**Issue by ghost** [xxxyanchenxxx/VirtualAppEx#16]
安卓 9 上,微信是无法启动的-_-||

**Comment by sunnygql** [comment]
mInitialApplication = LoadedApk.makeApplication.call(data.info, false, null);
这里报错: mInitialApplication = null

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Application.getApplicationContext()' on a null object reference
