### ISSUE TITLE
微信8.0及以上兼容问题

### ISSUE THREAD

**Issue by yangxiqiangs** [xxxyanchenxxx/VirtualAppEx#2]
android版本8.0及以上，微信的push进程会一直崩溃，导致登录流程无法走通，测试过几台8.0及以上的手机都会这样，8.0以下就没问题，请问有解决方案吗？

**Comment by xxxyanchenxxx** [comment]
看下crash的call statck

**Comment by z8806c** [comment]
测试了下 安卓9.0 没问题
